services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres # Replace with your username
      POSTGRES_PASSWORD: postgres # Replace with your password
      POSTGRES_DB: postgres # Replace with your database name
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend-network

  # redis:
  #   image: redis:latest
  #   container_name: redis-cache
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - redis_data:/data
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - backend-network

volumes:
  postgres_data:
  #redis_data:

networks:
  backend-network:
